# Generated by Django 4.0.3 on 2022-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('year', models.CharField(max_length=256, verbose_name='Year')),
                ('type', models.CharField(max_length=256, verbose_name='Type')),
            ],
        ),
    ]
