# Generated by Django 4.0.3 on 2022-04-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', upload_to='img_movie', verbose_name='Poster'),
            preserve_default=False,
        ),
    ]
