# Generated by Django 4.0.3 on 2022-04-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_movie', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='N/A', upload_to='img_movie', verbose_name='Poster'),
        ),
    ]
